# Generated by Django 3.1.7 on 2021-04-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphotil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hour',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
