# Generated by Django 3.1.7 on 2021-04-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphotil', '0005_matar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matar',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='matar',
            name='date_activiti',
        ),
    ]
