# Generated by Django 3.1.7 on 2021-04-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphotil', '0006_auto_20210425_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='matar',
            name='start_stiy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
